### ISSUE TITLE
URL is shortened on every upload

### ISSUE THREAD

**Issue by tomnorwood** [markusslima/bootstrap-filestyle#113]
Hi! 

We are running the latest bootstrap filestyle 1.2.1. Our forms have multiple file upload buttons where the user will upload documents, go back another time to the same form and upload a new version. On the second submit, our code takes the relative URL and turns it into a full URL. The issue is that the filestyle library is shortening the relative URL on every submit until it becomes too short for the underlying Umbraco layer.

Please help!

Tom

**Comment by markusslima** [comment]
I regret to inform you but the plugin does not change the url of the requested image. What happens is that browsers deliver the url in different ways. This operation is standard browsers and you will have to adapt to it, since javascript does not have access to the file system to return a different url.
