### ISSUE TITLE
text-align: center not work 

### ISSUE THREAD

**Issue by FurankuDesu** [markusslima/bootstrap-filestyle#77]
i try this:
text-align: center in div
div->p->input file

but not work text-align: center, i need some help, thank you

**Comment by lifeinafolder** [comment]
Are you using bootstrap? If yes, it wont work.

This doesn't work because of the following class ``group-span-filestyle`` in the code  on the ``input``.

That class matches the attribute wildcard selector ``class*="span"`` that atleast bootstrap 2 has and puts styles like ``float:left;`` on all elements having ``span`` as a word in the classname.

**Comment by lifeinafolder** [comment]
@markusslima Any particular reason to use ``group-span-filestyle`` specifically as the classname?

**Comment by markusslima** [comment]
This class is only for grouping elements. She has no css style in-built.

**Comment by markusslima** [comment]
To centralize all filestyle you must change the bootstrap standards. For the plugin receives no css style. It will be up to you, you can center the plugin in various ways.
